title:          "OS211"
author:     "rafidirg"
address:    "Bekasi"
urlweb:     "https://rafidirg.github.io/os211"
urlgithub:      "https://github.com/rafidirg/os211"
urlghpage:      "https://rafidirg.github.io/os211"
mygithub:       "https://github.com/rafidirg"
keywords:       "jekyll, testing"
sitemap:        "true"
plugins:
        - jekyll-sitemap
        - jekyll-seo-tag
